### ISSUE TITLE
The sample code is not working in my project

### ISSUE THREAD

**Issue by ugurdoksan** [alejandro-du/paged-tabs#2]
Here is the all code:

 `
@Route( "" )
@Theme( Lumo.class )
@Viewport( "width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes" )
public class AppUI extends HorizontalLayout {

	public AppUI( ) {

		setSizeFull( );
		setAlignItems( Alignment.CENTER );

		PagedTabs tabs = new PagedTabs( );
		tabs.add( new Span( "Close me" ), "Closeable" );
		add( tabs );
	}
}
`

Here is the stacktrace:
`aused by: java.lang.NullPointerException
	at org.vaadin.tabs.PagedTabs.select(PagedTabs.java:40)
	at org.vaadin.tabs.PagedTabs.lambda$new$9b1b5227$1(PagedTabs.java:32)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:133)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:358)
	at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:318)
	at com.vaadin.flow.component.tabs.Tabs.add(Tabs.java:94)
	at org.vaadin.tabs.PagedTabs.add(PagedTabs.java:91)
	at org.vaadin.tabs.PagedTabs.add(PagedTabs.java:85)
	at org.vaadin.tabs.PagedTabs.add(PagedTabs.java:62)
	at org.vaadin.tabs.PagedTabs.add(PagedTabs.java:58)
	at co.phisoftware.client.AppUI.<init>(AppUI.java:37)
	... 51 more
`

Here is dependency:
`
<dependency>
   <groupId>org.vaadin.tabs</groupId>
   <artifactId>paged-tabs</artifactId>
   <version>1.1.0</version>
</dependency>
`

**Comment by ugurdoksan** [comment]
Here is all of the stacktrace:

`
There was an exception while trying to navigate to '' with the exception message 'Unable to create an instance of 'co.phisoftware.client.AppUI'. The constructor threw an exception.'
java.lang.IllegalArgumentException: Unable to create an instance of 'co.phisoftware.client.AppUI'. The constructor threw an exception.
	at com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:510)
	at com.vaadin.flow.internal.ReflectTools.createInstance(ReflectTools.java:447)
	at com.vaadin.flow.di.DefaultInstantiator.getOrCreate(DefaultInstantiator.java:65)
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:158)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:116)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:115)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:167)
	at com.vaadin.flow.router.Router.handleNavigation(Router.java:202)
	at com.vaadin.flow.router.Router.navigate(Router.java:173)
	at com.vaadin.flow.router.Router.initializeUI(Router.java:94)
	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1051)
	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:393)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1486)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:300)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:479)
	... 46 more
Caused by: java.lang.NullPointerException
	at org.vaadin.tabs.PagedTabs.select(PagedTabs.java:40)
	at org.vaadin.tabs.PagedTabs.lambda$new$9b1b5227$1(PagedTabs.java:32)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:133)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:358)
	at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:318)
	at com.vaadin.flow.component.tabs.Tabs.add(Tabs.java:94)
	at org.vaadin.tabs.PagedTabs.add(PagedTabs.java:91)
	at org.vaadin.tabs.PagedTabs.add(PagedTabs.java:85)
	at org.vaadin.tabs.PagedTabs.add(PagedTabs.java:62)
	at org.vaadin.tabs.PagedTabs.add(PagedTabs.java:58)
	at co.phisoftware.client.AppUI.<init>(AppUI.java:28)
	... 51 more
`

**Comment by marcelo107** [comment]
@ugurdoksan What version of Vaadin are you using? I encountered the same error when I tied upgrading to 10.0.5. The error is not present in 10.0.1. @alejandro-du any chance you could upgrade the Vaadin version of the add-on so it is compatabile with at least version 10.0.5?

**Comment by alejandro-du** [comment]
Vaadin 10.0.5 broke the component. `paged-tabs` 1.1.1 fixes the problem.

**Comment by ugurdoksan** [comment]
@alejandro-du The Vaadin version I am using is v10.0.6.

**Comment by alejandro-du** [comment]
Please try it out and let me know if the issue persists.

**Comment by ugurdoksan** [comment]
@alejandro-du  the problem is solved. Thanks.

irrelevant:
Do you have any plan for adding setOrientation method for PagedTabs? I opened an issue about it.
